function [alpha2_m, cax_alpha,alpha2] = fct_alpha2(model,nabla_phi,t)
% This function plots carcterisation of stretching (alpha^2, beta/alpha,
% mesochronic vorticity, FTLEs)
%

day = num2str(floor(t*model.advection.dt_adv/(3600*24)));
loc_colorbar = 'southoutside';
colormap_ = 'default';
% colormap_ = 'jet';

% Grid
x = model.grid.x_ref;
y = model.grid.y_ref;

%% Caracterisation of the stretching

% alpha^2
alpha2 = 1/2*sum(sum(nabla_phi.^2,4),3)-1;
alpha2 = alpha2 .* (alpha2 >eps );

% Beta/alpha
beta_alpha = sqrt((alpha2+2)./alpha2);
s=size(beta_alpha);
id_beta = isinf(beta_alpha(:));
beta_alpha(id_beta)=0;
beta_alpha=reshape(beta_alpha,s);

% Mesochronic velocity
nabla_meso_v = nabla_phi;
nabla_meso_v(:,:,1,1) = nabla_meso_v(:,:,1,1)-1;
nabla_meso_v(:,:,2,2) = nabla_meso_v(:,:,2,2)-1;
time_t = model.advection.dt_adv*t;
nabla_meso_v = 1/ time_t * nabla_meso_v;

% Mesochronic vorticity
meso_vort = (nabla_meso_v(:,:,2,1) ...
    - nabla_meso_v(:,:,1,2)).^2 /2 ;
plot_meso_vort=meso_vort;

%% Plot

taille_police = 12;
width=9;
% width=12;
height=4;
figure5=figure(5);
close(figure5);
figure5=figure(5);
set(figure5,'Units','inches', ...
    'Position',[10 20 width height], ...
    'PaperPositionMode','auto');

subplot(1,3,2)
%         subplot(2,2,3)
%         subplot(2,3,4)
imagesc(x,y,alpha2'/time_t^2);
% imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
axis equal
axis xy
colormap(colormap_)
colorbar('location',loc_colorbar)
%         in mesohyperbolic areas
% title('$\alpha^2$',...
title('$\alpha^2 / t^2$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])
%         colorbar
%         title('$log(\alpha^2)$ in mesohyperbolic areas')
%        figure(8)

if strcmp(model.type_data(1:min(end,11)),'globcurrent')
    % warning('caxis set up');
    caxis([0 5e-11]);
end
cax = caxis;
if nargout >= 2
    cax_alpha = cax(2);
end

subplot(1,3,1)
imagesc(x,y,((plot_meso_vort))');
% imagesc(x(2:end-1),y(2:end-1),((plot_meso_vort(2:end-1,2:My-3)))');
%         imagesc(x,y,(abs(plot_meso_vort(:,1:My-2)))');
axis xy
axis equal
caxis(cax);
colormap(colormap_)
colorbar('location',loc_colorbar)
%         title('$log \left (| \breve \omega | \right )$',...
% title('$ \breve \omega ^2 \ t^2 /2 $',...
title('$ \breve \omega ^2 /2 $',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])



subplot(1,3,3)
%         subplot(2,2,4)
%         subplot(2,3,5)
s_beta_alpha = size(beta_alpha);
m_beta = (beta_alpha > max(beta_alpha(:))/2);
beta_alpha(m_beta)=0;
beta_alpha=reshape(beta_alpha,s_beta_alpha);
imagesc(x,y,(beta_alpha)');
% imagesc(x(2:end-1),y(2:end-1),(beta_alpha((2:end-1),2:My-3))');
set(gca,'CLim',[0 5]);
axis equal
axis xy
colormap(colormap_)
colorbar('location',loc_colorbar)
title('$\beta / \alpha$',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times');
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])
drawnow


eval( ['print -depsc ' model.folder.folder_simu '/mezic_mixing/' ...
    num2str(day) '.eps']);

%% PLot longitude-latitude
if isfield(model.grid,'lonlat')
    
    % Grid
    x = model.grid.x_ref;
    y = model.grid.y_ref;
    lon = model.grid.lonlat.lon;
    lat = model.grid.lonlat.lat;
    lonlat_ref = model.grid.lonlat.lonlat_ref;
    
    [LON,LAT]=ndgrid(lon,lat);
    for i=1:2
        for j=1:2
            nabla_phi_lonlat(:,:,i,j) = ...
                fct_cart2sph(x,y,nabla_phi(:,:,i,j),LON,LAT,lonlat_ref);
        end
    end
    
    x = lon;y=lat;
    nabla_phi = nabla_phi_lonlat; clear nabla_phi_lonlat;
    
    nabla_meso_v = nabla_phi;
    nabla_meso_v(:,:,1,1) = nabla_meso_v(:,:,1,1)-1;
    nabla_meso_v(:,:,2,2) = nabla_meso_v(:,:,2,2)-1;
    time_t = model.advection.dt_adv*t;
    nabla_meso_v = 1/ time_t * nabla_meso_v;
    
    width=9;
    % width=12;
    height=4;
    figure5=figure(5);
    close(figure5);
    figure5=figure(5);
    set(figure5,'Units','inches', ...
        'Position',[10 20 width height], ...
        'PaperPositionMode','auto');
    
    alpha2 = 1/2*sum(sum(nabla_phi.^2,4),3)-1;
    alpha2 = alpha2 .* (alpha2 >eps );
    %         alpha2 = alpha2 .* (alpha2 >=0 );
    beta_alpha = sqrt((alpha2+2)./alpha2);
    s=size(beta_alpha);
    id_beta = isinf(beta_alpha(:));
    beta_alpha(id_beta)=0;
    beta_alpha=reshape(beta_alpha,s);
    % beta_alpha=reshape(beta_alpha,[model.grid.MX-2]);
    % %        figure(7)
    subplot(1,3,2)
    %         subplot(2,2,3)
    %         subplot(2,3,4)
    imagesc(x,y,alpha2'/time_t^2);
    % imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
    axis equal
    axis xy
    colormap(colormap_)
    colorbar('location',loc_colorbar)
    %         in mesohyperbolic areas
    % title('$\alpha^2$',...
    title('$\alpha^2 / t^2$',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times');
    set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',11,...
        'FontName','Times')
    ylabel('Lat($^{\circ}$)',...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',taille_police,...
        'FontName','Times')
    xlabel('Lon($^{\circ}$)',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',taille_police,...
        'FontName','Times')
    axis([x(1) x(end) y(1) y(end)])
    %         colorbar
    %         title('$log(\alpha^2)$ in mesohyperbolic areas')
    %        figure(8)
    
    if strcmp(model.type_data(1:min(end,11)),'globcurrent')
        % warning('caxis set up');
        caxis([0 5e-11]);
    end
    cax = caxis;
    if nargout == 2
        cax_alpha = cax(2);
    end
    
    % meso_vort = time_t^2*(nabla_meso_v(:,:,2,1) ...
    meso_vort = (nabla_meso_v(:,:,2,1) ...
        - nabla_meso_v(:,:,1,2)).^2 /2 ;
    plot_meso_vort=meso_vort;
    
    subplot(1,3,1)
    imagesc(x,y,((plot_meso_vort))');
    % imagesc(x(2:end-1),y(2:end-1),((plot_meso_vort(2:end-1,2:My-3)))');
    %         imagesc(x,y,(abs(plot_meso_vort(:,1:My-2)))');
    axis xy
    axis equal
    caxis(cax);
    colormap(colormap_)
    colorbar('location',loc_colorbar)
    %         title('$log \left (| \breve \omega | \right )$',...
    % title('$ \breve \omega ^2 \ t^2 /2 $',...
    title('$ \breve \omega ^2 /2 $',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times');
    set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',11,...
        'FontName','Times')
    ylabel('Lat($^{\circ}$)',...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',taille_police,...
        'FontName','Times')
    xlabel('Lon($^{\circ}$)',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',taille_police,...
        'FontName','Times')
    axis([x(1) x(end) y(1) y(end)])
    
    
    
    subplot(1,3,3)
    %         subplot(2,2,4)
    %         subplot(2,3,5)
    s_beta_alpha = size(beta_alpha);
    m_beta = (beta_alpha > max(beta_alpha(:))/2);
    beta_alpha(m_beta)=0;
    beta_alpha=reshape(beta_alpha,s_beta_alpha);
    imagesc(x,y,(beta_alpha)');
    % imagesc(x(2:end-1),y(2:end-1),(beta_alpha((2:end-1),2:My-3))');
    set(gca,'CLim',[0 5]);
    axis equal
    axis xy
    colormap(colormap_)
    colorbar('location',loc_colorbar)
    title('$\beta / \alpha$',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times');
    set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',11,...
        'FontName','Times')
    ylabel('Lat($^{\circ}$)',...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',taille_police,...
        'FontName','Times')
    xlabel('Lon($^{\circ}$)',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',taille_police,...
        'FontName','Times')
    axis([x(1) x(end) y(1) y(end)])
    drawnow
    eval( ['print -depsc ' model.folder.folder_simu ...
        '/mezic_mixing_lonlat/' ...
        num2str(day) '.eps']);
    
    
    %% FTLE
    
    FTLE = 1 + alpha2 .* ( 1 + beta_alpha );
    FTLE = 1/(2*time_t) * log(FTLE);
    
    width=9;
    % width=12;
    height=4;
    figure6=figure(6);
    close(figure6);
    figure6=figure(6);
    set(figure6,'Units','inches', ...
        'Position',[10 20 width 2*height], ...
        'PaperPositionMode','auto');
    
    imagesc(x,y,FTLE');
    % imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
    axis equal
    axis xy
    colormap(colormap_)
    colorbar('location',loc_colorbar)
    %         in mesohyperbolic areas
    % title('$\alpha^2$',...
    title('FTLE',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times');
    set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',11,...
        'FontName','Times')
    ylabel('Lat($^{\circ}$)',...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',taille_police,...
        'FontName','Times')
    xlabel('Lon($^{\circ}$)',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',taille_police,...
        'FontName','Times')
    axis([x(1) x(end) y(1) y(end)])
    
    drawnow
    eval( ['print -depsc ' model.folder.folder_simu ...
        '/mezic_mixing_lonlat/FTLE_' num2str(day) '.eps']);
    
    %% Only alpha
    
    
    width=9;
    % width=12;
    height=4;
    figure5=figure(5);
    close(figure5);
    figure5=figure(5);
    set(figure5,'Units','inches', ...
        'Position',[10 20 width 2*height], ...
        'PaperPositionMode','auto');
    
    imagesc(x,y,alpha2'/time_t^2);
    % imagesc(x(2:end-1),y(2:end-1),(alpha2((2:end-1),2:My-3))'/time_t^2);
    axis equal
    axis xy
    colormap(colormap_)
    colorbar('location',loc_colorbar)
    %         in mesohyperbolic areas
    % title('$\alpha^2$',...
    title('$\alpha^2 / t^2$',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'interpreter','latex',...
        'FontSize',12,...
        'FontName','Times');
    set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',11,...
        'FontName','Times')
    ylabel('Lat($^{\circ}$)',...
        'FontUnits','points',...
        'interpreter','latex',...
        'FontSize',taille_police,...
        'FontName','Times')
    xlabel('Lon($^{\circ}$)',...
        'interpreter','latex',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',taille_police,...
        'FontName','Times')
    axis([x(1) x(end) y(1) y(end)])
    %         colorbar
    %         title('$log(\alpha^2)$ in mesohyperbolic areas')
    %        figure(8)
    
    if strcmp(model.type_data(1:min(end,11)),'globcurrent')
        % warning('caxis set up');
        caxis([0 5e-11]);
    end
    cax = caxis;
    if nargout == 2
        cax_alpha = cax(2);
    end
    
    drawnow
    eval( ['print -depsc ' model.folder.folder_simu ...
        '/mezic_mixing_lonlat/alpha_' ...
        num2str(day) '.eps']);
    
    
    
end

alpha2_m = mean(alpha2(:));
