function w = fct_w_toy4(model)
% Create homogeneous Gaussian tracer with a spectrum slope -6
%

model.odg_b=1e4;
model.k_inf_on_k1 = 4;
model.slope_b_ini = -8;
phi = init_Spectrum(model);
w = gradient_ortho_perso(model.grid, phi);


%% Plots
vort = vorticity_perso(model.grid, w);

width=3.5;
height=3;
X0 = [0 0];

figure('Name','Angular velocity','NumberTitle','off','Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
x = model.grid.dX(1)*(0:model.grid.MX(1)-1);
y = model.grid.dX(2)*(0:model.grid.MX(2)-1);
imagesc(x,y,vort');
axis xy; axis equal;
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
colorbar
title('Vorticity',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'interpreter','latex',...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])

% Create the folders
fct_create_folder_plots(model)

eval( ['print -depsc ' model.folder.folder_simu '/vort_w.eps']);

