function w = fct_w_toy(model)
% Create an incompressible velocity with circle streamlines and an angular
% velocity which is Gaussian function of the distance at the origin
%

x = model.grid.dX(1)*(0:model.grid.MX(1)-1);
x=x-mean(x);
y = model.grid.dX(2)*(0:model.grid.MX(2)-1);
y=y-mean(y);
r = sqrt(bsxfun(@plus,(x').^2,(y).^2));

sigma = 0.05*sqrt(prod(model.grid.dX.*model.grid.MX)); % ~ Rossby radius
radius=0.2*sqrt(prod(model.grid.dX.*model.grid.MX));
ampli = model.coriolis.f0/2;
theta_dot = ampli * exp(-1/2*(r-radius).^2/sigma^2);

[x,y]=ndgrid(x,y);
w(:,:,1) = -y ; w(:,:,2) = x ;
w = 1/2 * bsxfun(@times,w,theta_dot);


%% Plots

vort = vorticity_perso(model.grid, w);

width=3.5;
height=3;
X0 = [0 0];
figure('Name','Angular velocity','NumberTitle','off','Units','inches', ...
    'Position',[X0(1) X0(2) width height], ...
    'PaperPositionMode','auto');
x = model.grid.dX(1)*(0:model.grid.MX(1)-1);
y = model.grid.dX(2)*(0:model.grid.MX(2)-1);
imagesc(x,y,vort');
axis xy; axis equal;
set(gca,...
    'Units','normalized',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',11,...
    'FontName','Times')
ylabel('y(m)',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
xlabel('x(m)',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'interpreter','latex',...
    'FontSize',11,...
    'FontName','Times')
colorbar
title('Vorticity',...
    'FontUnits','points',...
    'FontWeight','normal',...
    'FontSize',12,...
    'interpreter','latex',...
    'FontName','Times')
axis([x(1) x(end) y(1) y(end)])


